substitutions:
  device_name: family-room-play
  friendly_name: Family Room Play
  min_brightness: "60"
  max_brightness: "980"
  min_brightness_pct: "6"
  max_brightness_pct: "98"

esphome:
  name: $device_name
  friendly_name: $friendly_name
  comment: "TreatLife DS03 Fan and Light Switch BK7231N v2.1.6"
  on_boot:
    priority: -100
    then:
      - delay: 5s
      - number.set:
          id: light_brightness
          value: $max_brightness_pct

bk72xx:
  board: generic-bk7231n-qfn32-tuya

<<: !include .common.yaml

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 115200

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

  # Expose ESPHome version as sensor.
  - platform: version
    name: ESPHome Version
    
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID
    bssid:
      name: BSSID

light:
  - platform: tuya
    name: Dimmer
    switch_datapoint: 101
    dimmer_datapoint: 6
    min_value_datapoint: 105
    min_value: $min_brightness
    max_value: $max_brightness

fan:
  - platform: tuya
    name: Fan
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4

select:
  - platform: tuya
    enum_datapoint: 3
    name: Fan Speed
    optimistic: true
    options:
      0: Speed 1
      1: Speed 2
      2: Speed 3
      3: Speed 4
  - platform: tuya
    enum_datapoint: 106
    entity_category: config
    name: Dimming Mode
    optimistic: true
    options:
      0: Mode 1
      1: Mode 2
      2: Mode 3

number:
  - platform: tuya
    number_datapoint: 6
    name: Brightness
    id: light_brightness
    unit_of_measurement: "%"
    min_value: $min_brightness_pct
    max_value: $max_brightness_pct
    step: 1
    multiply: 10
    mode: BOX
  - platform: tuya
    number_datapoint: 105
    name: Brightness Mininum
    unit_of_measurement: "%"
    min_value: 1
    max_value: 100
    step: 1
    multiply: 10
    entity_category: config
    mode: BOX

  - platform: tuya
    number_datapoint: 102
    name: (Unconfirmed) Fan Countdown
    unit_of_measurement: "minutes"
    min_value: 0
    max_value: 1440
    step: 1
    entity_category: config
  - platform: tuya
    number_datapoint: 103
    name: (Unconfirmed) Light Count Down
    unit_of_measurement: "minutes"
    min_value: 0
    max_value: 1440
    step: 1
    entity_category: config
  - platform: tuya
    number_datapoint: 108
    name: (Unconfirmed) Indicator
    min_value: 0
    max_value: 2
    step: 1
    entity_category: config
