substitutions:
  device_name: fireplace-fan
  friendly_name: Fireplace Fan
  description: "TreatLife DS02F Fan Controller BK7231T"

esphome:
  name: $device_name
  friendly_name: $friendly_name
  comment: $description

bk72xx:
  board: generic-bk7231t-qfn32-tuya

<<: !include .common.yaml

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 115200

fan:
  - platform: tuya
    name: Fan
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4

switch:
  - platform: tuya
    switch_datapoint: 1
    name: Switch
    entity_category: config

number:
  - platform: tuya
    number_datapoint: 2
    name: Countdown
    unit_of_measurement: seconds
    min_value: 0
    max_value: 86400
    step: 1
    entity_category: config
  - platform: tuya
    number_datapoint: 101
    name: Indicator
    min_value: 0
    max_value: 1
    step: 1
    entity_category: config

select:
  - platform: tuya
    enum_datapoint: 3
    name: Speed
    optimistic: true
    options:
      0: Speed 1
      1: Speed 2
      2: Speed 3
      3: Speed 4
