web_server:
  auth: 
    username: !secret web_server_auth_user
    password: !secret web_server_auth_password

captive_portal:

mdns:

# Uncomment to add local time and avoid the "LOCAL_TIME_QUERY is not handled because time is not configured" log error
time:
  - platform: homeassistant
    id: homeassistant_time
tuya:
  time_id: homeassistant_time

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$friendly_name Fallback Hotspot"
    password: !secret fallback_hotspot_password

debug:
  update_interval: 30s

button:
  - platform: restart
    name: Restart

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

  # Expose ESPHome version as sensor.
  - platform: version
    name: ESPHome Version
    
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID
    bssid:
      name: BSSID

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
    filters:
      - delta: 0.01
      - throttle: 300s

  - platform: uptime
    name: Uptime
    filters:
      - throttle: 300s
