substitutions:
  device_name: henry
  friendly_name: Henry
  description: "TreatLife DS02S Single Pole Dimmer"

esphome:
  name: $device_name
  friendly_name: $friendly_name
  comment: $description

bk72xx:
  board: generic-bk7231t-qfn32-tuya

# Enable logging
logger:

web_server:
  auth: 
    username: !secret web_server_auth_user
    password: !secret web_server_auth_password

captive_portal:

mdns:

# Uncomment to add local time and avoid the "LOCAL_TIME_QUERY is not handled because time is not configured" log error
time:
  - platform: homeassistant
    id: homeassistant_time
tuya:
  time_id: homeassistant_time

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$friendly_name Fallback Hotspot"
    password: !secret fallback_hotspot_password

debug:
  update_interval: 30s

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 115200

button:
  - platform: restart
    name: Restart

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

  # Expose ESPHome version as sensor.
  - platform: version
    name: ESPHome Version
    
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID
    bssid:
      name: BSSID

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
    filters:
      - delta: 0.01
      - throttle: 300s

  - platform: uptime
    name: Uptime
    filters:
      - throttle: 300s

light:
  - platform: tuya
    name: Dimmer
    switch_datapoint: 1
    dimmer_datapoint: 2
    min_value_datapoint: 3
    min_value: 10
    max_value: 980

switch:
  - platform: tuya
    switch_datapoint: 1
    name: Switch
    entity_category: config

number:
  - platform: tuya
    number_datapoint: 2
    name: Brightness Raw
    min_value: 10
    max_value: 980
    step: 1
  - platform: tuya
    number_datapoint: 3
    name: Brightness Min Raw
    min_value: 10
    max_value: 1000
    step: 1
    entity_category: config
  - platform: tuya
    number_datapoint: 102
    name: Count Down Minutes
    min_value: 0
    max_value: 1440
    step: 1
    entity_category: config
  - platform: tuya
    number_datapoint: 104
    name: Indicator
    min_value: 0
    max_value: 1
    step: 1
    entity_category: config

select:
  - platform: tuya
    enum_datapoint: 4
    entity_category: config
    name: Dimming Mode
    optimistic: true
    options:
      0: Led
      1: Incandescent
      2: Halogen
